// src/components/media/tiles/artist-tile.svelte
<script lang="ts">
	import ButtonPlay from '../../../components/buttons/button-play.svelte';

	export let src: string;
	export let title: string;
	export let id: string;
</script>

<div class="artist-tile">
	<div class="artist-tile__overlay-wrapper">
		<a class="artist-tile__overlay-wrapper__overlay" href={`/media/artist/${id}`}>
			<ButtonPlay color="white" size="3rem" />
		</a>
		<img {src} alt="Album Art" loading="lazy" />
	</div>
	<div class="artist-info">
		<a class="artist-title" href={`/media/artist/${id}`}>{title}</a>
	</div>
</div>

<style lang="scss">
	@use '../../../variables.scss' as *;

	.artist-tile {
		display: flex;
		flex-direction: column;
		max-width: 8.5rem;

		img {
			aspect-ratio: 1;
			border-radius: 50%;
			max-height: 8.5rem;
			max-width: 8.5rem;
			min-width: 8.5rem;
			min-height: 8.5rem;
		}

		.artist-tile__overlay-wrapper {
			position: relative;
			width: 100%;
			height: 100%;
			aspect-ratio: 1;

			&:hover .artist-tile__overlay-wrapper__overlay {
				opacity: 1;
			}

			&:hover .artist-tile__overlay-wrapper__overlay,
			&:focus-visible .artist-tile__overlay-wrapper__overlay,
			&:focus-within .artist-tile__overlay-wrapper__overlay {
				background-color: rgba(0, 0, 0, 0.4);
				opacity: 1;
			}

			.artist-tile__overlay-wrapper__overlay {
				display: flex;
				justify-content: center;
				align-items: center;
				position: absolute;
				width: 100%;
				height: 100%;
				max-height: 8.5rem;
				max-width: 8.5rem;
				min-width: 8.5rem;
				min-height: 8.5rem;
				border-radius: 50%;
				transition: all 0.2s ease-in-out;
				opacity: 0;
			}
		}
		.artist-info {
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			margin-top: 0.5rem;
			margin-bottom: 0.5rem;
			text-align: center;
			max-width: 100%;
			overflow: hidden;
			color: var(--text);

			.artist-title {
				&:hover {
					text-decoration: underline;
				}
			}
		}
	}
</style>

// libs/core/src/lib/artist-tile/artist-tile.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'core-artist-tile',
  standalone: true,
  imports: [CommonModule],
  template: `<div class="artist-tile-wrapper">
    <div class="artist-tile">
      <div class="artist-tile__image-wrapper">
        <img [src]="image" class="artist-tile-wrapper__image-wrapper__image" />
        <div class="artist-tile-wrapper__image-overlay"></div>
      </div>
      <p>{{ name }}</p>
    </div>
  </div>`,
  styles: [
    `
      :host {
        display: block;
        position: relative;

        &:hover {
          .artist-tile-wrapper__image-overlay {
            display: block !important;
          }
        }
      }

      .artist-tile-wrapper {
        position: relative;
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        align-self: flex-start;
      }

      .artist-tile {
        flex: 1;
        align-self: flex-start;
        position: relative;

        .artist-tile__image-wrapper {
          position: relative;
          width: 100%;
          border-radius: 8px;

          .artist-tile-wrapper__image-overlay {
            display: none;
            position: absolute;
            width: 100%;
            height: calc(100% - 0.85rem);
            top: 0;
            bottom: 0;
            background-color: oklch(0 0 0 / 40%);
            border-radius: 8px;
            overflow: hidden;
            border-radius: 50%;
          }

          .artist-tile-wrapper__image-wrapper__image {
            flex: 1;
            background: var(--backgroundColor, black);
            border-radius: 50%;
            height: 8vw;
            margin-bottom: 0.5rem;
            flex: 1 1 0px;
          }
        }
      }

      p {
        color: var(--textColor);
        text-align: center;
        margin: 0;
        overflow: hidden;

        &:hover {
          text-decoration: underline;
          cursor: pointer;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArtistTileComponent {
  @Input() name = '';
  @Input() image = '';
  @Input() tileSize = 8;
}
